name: Build Windows Portable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-windows
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Ensure Git LFS files
        shell: pwsh
        run: |
          git lfs install
          git lfs pull

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: potree-electron
        run: |
          npm ci

      - name: Build portable
        working-directory: potree-electron
        run: |
          npm run dist

      - name: Archive EXE to ZIP
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path "potree-electron/dist/*.exe" | Select-Object -First 1
          if (-not $exe) { Write-Error "Executable .exe not found in dist"; exit 1 }
          $zip = "potree-electron/dist/potree-web-packager-win.zip"
          if (Test-Path $zip) { Remove-Item -Force $zip }
          Compress-Archive -Path $exe.FullName -DestinationPath $zip

      - name: Upload artifacts (ZIP + EXE)
        uses: actions/upload-artifact@v4
        with:
          name: potree-web-packager-win
          path: |
            potree-electron/dist/potree-web-packager-win.zip
            potree-electron/dist/*.exe

      - name: Upload Release assets (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            potree-electron/dist/potree-web-packager-win.zip
            potree-electron/dist/*.exe
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Continuous Release (on main)
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: continuous
          name: Continuous build
          draft: false
          prerelease: true
          files: |
            potree-electron/dist/potree-web-packager-win.zip
            potree-electron/dist/*.exe
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

